-- Seed guests and groups from bd_invitados.csv
-- Generated: 2026-02-12T21:43:34.887189

with groups_data(name) as (
  values
  ('ANTONBELLEGGI'),
  ('CASTROGALLARDO'),
  ('CASUSCELLICATALANO'),
  ('COSIO'),
  ('GARCIAILARI'),
  ('GARCIATOLOSA'),
  ('LOPEZBARBALACE'),
  ('MENDEZNERI'),
  ('NAVARRETAFRANCO'),
  ('PAISADAN'),
  ('PERALTADESALVO'),
  ('SALGUEIROBOGADILLA'),
  ('SOLARIORELIA'),
  ('SOMMABAVIELLO'),
  ('SOMMALADINO'),
  ('SOMMAMARINI'),
  ('TONELLOMOYA'),
  ('VILA'),
  ('VILAACOSTA'),
  ('VILAANTON'),
  ('VILAFRAGA'),
  ('VILASALGUEIRO'),
  ('VILLARINOMILER')
)
, insert_groups as (
  insert into groups (name)
  select name from groups_data
  on conflict (name) do nothing
  returning id, name
)
, groups_map as (
  select id, name from groups where name in ('ANTONBELLEGGI', 'CASTROGALLARDO', 'CASUSCELLICATALANO', 'COSIO', 'GARCIAILARI', 'GARCIATOLOSA', 'LOPEZBARBALACE', 'MENDEZNERI', 'NAVARRETAFRANCO', 'PAISADAN', 'PERALTADESALVO', 'SALGUEIROBOGADILLA', 'SOLARIORELIA', 'SOMMABAVIELLO', 'SOMMALADINO', 'SOMMAMARINI', 'TONELLOMOYA', 'VILA', 'VILAACOSTA', 'VILAANTON', 'VILAFRAGA', 'VILASALGUEIRO', 'VILLARINOMILER')
)
, guests_data(first_name, last_name, phone, group_name) as (
  values
  ('Paula', 'Salgueiro', '1123432291', NULL),
  ('Federico', 'Bilik', '1157169938', NULL),
  ('Leandro', 'Pais', '1164690945', NULL),
  ('Sergio', 'Pais', '2914222274', 'PAISADAN'),
  ('Silvana', 'Adán', '2914747344', 'PAISADAN'),
  ('Susana', 'Vila', '1153220134', 'VILASALGUEIRO'),
  ('Antonio', 'Salgueiro', '1151856594', 'VILASALGUEIRO'),
  ('Ernesto', 'Salgueiro', NULL, 'SALGUEIROBOGADILLA'),
  ('Mariela', 'Bogadilla', NULL, 'SALGUEIROBOGADILLA'),
  ('Julieta', 'Salgueiro', NULL, 'SALGUEIROBOGADILLA'),
  ('Nahuel', 'Salgueiro', NULL, 'SALGUEIROBOGADILLA'),
  ('Gerardo', 'Vila', NULL, 'VILA'),
  ('Joaquin', 'Vila', NULL, 'VILA'),
  ('Roger', 'Vila', NULL, 'VILAACOSTA'),
  ('Barbara', 'Acosta', NULL, 'VILAACOSTA'),
  ('Flor', 'Acosta', NULL, 'VILAACOSTA'),
  ('Bruno', 'Vila', NULL, 'VILAACOSTA'),
  ('Joanma', 'Vila', NULL, 'VILAFRAGA'),
  ('Brisa', 'Fraga', NULL, 'VILAFRAGA'),
  ('Andrea', 'Vila', NULL, 'VILAANTON'),
  ('Daniel', 'Anton', NULL, 'VILAANTON'),
  ('Ignacio', 'Anton', NULL, 'VILAANTON'),
  ('Victoria', 'Anton', NULL, 'ANTONBELLEGGI'),
  ('Nicolas', 'Belleggi', NULL, 'ANTONBELLEGGI'),
  ('Alicia', 'Belleggi', NULL, 'ANTONBELLEGGI'),
  ('Hijo Nicolas', 'Belleggi', NULL, 'ANTONBELLEGGI'),
  ('Gian Franco', 'Befart', NULL, NULL),
  ('Mauro', 'Maffi', NULL, NULL),
  ('Leandro', 'Garcia', '1154121251', 'GARCIAILARI'),
  ('Natalia', 'Ilari', NULL, 'GARCIAILARI'),
  ('Delfina', 'Garcia', NULL, 'GARCIAILARI'),
  ('Olivia', 'Garcia', NULL, 'GARCIAILARI'),
  ('Camila', 'Del Valle', '1149377935', NULL),
  ('Luz', 'Castro', NULL, 'CASTROGALLARDO'),
  ('Facundo', 'Gallardo', NULL, 'CASTROGALLARDO'),
  ('Yasmin', 'Aylu', NULL, NULL),
  ('Tamara', 'Solari', '1150260809', 'SOLARIORELIA'),
  ('Gabriel', 'Orelia', NULL, 'SOLARIORELIA'),
  ('Tamara', 'Aquino', '1170671671', NULL),
  ('Camila', 'Aquino', '1131616556', NULL),
  ('Brian', 'Aquino', NULL, NULL),
  ('Luciano', 'Siculin', '1133587771', NULL),
  ('Alejandro', 'Attento', '1155784250', NULL),
  ('Delfina', 'Nastaro', '1128685246', NULL),
  ('Blas', 'Gonzalez', '1162918129', NULL),
  ('Leonela', 'Villarino', NULL, 'VILLARINOMILER'),
  ('Nicolas', 'Miler', NULL, 'VILLARINOMILER'),
  ('Ciro', 'Miler', NULL, 'VILLARINOMILER'),
  ('Erika', 'Rodriguez', NULL, NULL),
  ('Alejandra', 'Casuscelli', '1138520403', NULL),
  ('Santiago', 'Guimera', '1159497440', NULL),
  ('Alejandro', 'Martinez', NULL, NULL),
  ('Flor', 'Martin', NULL, NULL),
  ('Micaela', 'Vandoni', '1122553148', NULL),
  ('Martin', 'Mendez', '1123863165', 'MENDEZNERI'),
  ('Luciana', 'Neri', NULL, 'MENDEZNERI'),
  ('Mateo', 'Neri', NULL, 'MENDEZNERI'),
  ('Leandro', 'Santo', NULL, NULL),
  ('Lautaro', 'Lopez', NULL, 'LOPEZBARBALACE'),
  ('Florencia', 'Barbalace', NULL, 'LOPEZBARBALACE'),
  ('Rodolfo', 'Solari', NULL, NULL),
  ('Ignacio', 'Garcia', NULL, 'GARCIATOLOSA'),
  ('Ariadna', 'Toloza', NULL, 'GARCIATOLOSA'),
  ('Facundo', 'Navarreta', '1138986039', 'NAVARRETAFRANCO'),
  ('Paloma', 'Franco', NULL, 'NAVARRETAFRANCO'),
  ('Ezequiel', 'Allio', NULL, NULL),
  ('Lara', 'Casuscelli', '1165330602', 'CASUSCELLICATALANO'),
  ('Daniel', 'Catalano', '1158519525', 'CASUSCELLICATALANO'),
  ('Leandro', 'Tonello', '1122538399', 'TONELLOMOYA'),
  ('Desire', 'Moya', NULL, 'TONELLOMOYA'),
  ('Claudia', 'Baviello', '1150049285', 'SOMMABAVIELLO'),
  ('Gabriel', 'Somma', '1132917671', 'SOMMABAVIELLO'),
  ('German', 'Somma', '1131210190', 'SOMMALADINO'),
  ('Romina', 'Ladino', '1168047787', 'SOMMALADINO'),
  ('Antonella', 'Somma', NULL, 'SOMMALADINO'),
  ('Gerardo', 'Somma', '2262675803', 'SOMMAMARINI'),
  ('Julia', 'Marini', '2262675801', 'SOMMAMARINI'),
  ('Maria Teresa', 'Gargiulo', NULL, 'SOMMAMARINI'),
  ('Guadalupe', 'Nunez', NULL, NULL),
  ('Mia', 'Somma', NULL, NULL),
  ('Agustina', 'Ruso', NULL, NULL),
  ('Iara', 'Peralta', '1165727408', 'PERALTADESALVO'),
  ('Nahuel', 'De Salvo', '1140225202', 'PERALTADESALVO'),
  ('Lorenzo', 'Gomez', NULL, 'PERALTADESALVO'),
  ('Andana', 'Turrin', '1144448967', NULL),
  ('Natalia', 'Rodriguez', '1126204934', NULL),
  ('Milagros', 'Esposito', '1173635103', NULL),
  ('Emilia', 'Maine', '1125151585', NULL),
  ('Elisa', 'Cosio', '1179008944', 'COSIO'),
  ('Claudio', 'Cosio', '1131092940', 'COSIO')
)
insert into guests (first_name, last_name, phone, group_id)
select
  gd.first_name,
  gd.last_name,
  gd.phone,
  gm.id
from guests_data gd
left join groups_map gm on gm.name = gd.group_name;
